# Generated by Django 3.2.12 on 2022-03-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("learning_resources", "0005_create_unique_constraints")]

    operations = [migrations.RenameModel(old_name="Categories", new_name="Category")]
