# Generated by Django 3.2.12 on 2022-05-02 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0009_change_ratings_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningobjectusage",
            name="used_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="learning_objects_used",
                to="learning_resources.system",
            ),
        ),
    ]
