# Generated by Django 3.2.12 on 2022-05-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0010_usage_system_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="creator_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
