# Generated by Django 3.2.12 on 2022-05-06 19:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0011_add_system_creator_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningobject",
            name="description",
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name="learningobject",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="LearningObjectFile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_route", models.FilePathField()),
                (
                    "learning_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="learning_resources.learningobject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
