version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/repositorium
    command: gunicorn repositorium.wsgi:application --bind 0.0.0.0:3050
    ports:
      - 3050:3050
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redisdata:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/repositorium
    depends_on:
      - db
      - redis
  beat:
    build:
      context: .
      dockerfile: Dockerfile.beat
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - .:/beatdata
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redisdata:
  beatdata:
