version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/repositorium
    command: gunicorn repositorium.wsgi:application --bind 0.0.0.0:3050
    ports:
      - 3050:3050
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
