# Generated by Django 3.2.12 on 2022-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0003_add_systems_user_field"),
        ("users", "0001_create_user_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="systems",
            field=models.ManyToManyField(
                related_name="users", to="learning_resources.System"
            ),
        )
    ]
